if command -v proton &>/dev/null; then
  PROTON_ENABLE_WAYLAND=1
  PROTON_NO_WM_DECORATION=1
  PROTON_USE_NTSYNC=1
  unset PROTON_LOCAL_SHADER_CACHE
  # PROTON_PREFER_SDL=1
  # PROTON_NO_STEAMINPUT=1
  # PROTON_ENABLE_HDR=1
  # sudo pacman -S --noconform --needed vk-hdr-layer-kwin6-git
  # ENABLE_HDR_WSI=1

  __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
  __GL_SHADER_DISK_CACHE_SIZE=12000000000
  PROTON_DLSS_UPGRADE=1
  PROTON_FSR4_UPGRADE=1
  PROTON_XESS_UPGRADE=1

  #PROTON_NVIDIA_LIBS=1
  PROTON_NVIDIA_LIBS_NO_32BIT=1
  PROTON_NVIDIA_NVENC=1
  PROTON_NVIDIA_NVCUDA=1
  #PROTON_NVIDIA_NVML=1
  #PROTON_NVIDIA_NVOPTIX=1

  PROTON_ENABLE_NGX_UPDATER=1
  DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE=on
  DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE=on
  DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE=on
  DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest
  DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest
fi

if command -v wime &>/dev/null; then
  WINE_NO_WM_DECORATION=1
  WINE_PREFER_SDL_INPUT=1
  export WINEPREFIX="$XDG_DATA_HOME"/wine
fi

# NVIDIA
__GL_THREADED_OPTIMIZATION=1
__GL_SHADER_DISK_CACHE=1
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
mesa_glthread=true

# Homebrew
export HOMEBREW_NO_ANALYTICS=true

