continue_on_error: true
doublestar: true
exclude:
  - ./.cache
  - ./go
  - ./node_modules
  - ./vendor
  - ./.git
extensions:
  - yaml
  - yml
gitignore_excludes: true
gitignore_path: .gitignore
include: []
line_ending: lf
match_type: standard
output_format: default
regex_exclude: []
formatter:
  array_indent: 0
  disable_alias_key_correction: true
  disallow_anchors: false
  drop_merge_tag: false
  eof_newline: true
  force_array_style: ""
  include_document_start: false
  indent: 2
  indent_root_array: false
  indentless_arrays: false
  max_line_length: 120
  pad_line_comments: 1
  retain_line_breaks: false
  retain_line_breaks_single: false
  scan_folded_as_literal: false
  strip_directives: false
  trim_trailing_whitespace: true
  type: basic
