---
extends: default
rules:
  indentation:
    indent-sequences: true
    spaces: 2
  braces:
    forbid: false
    max-spaces-inside: 1
  brackets:
    forbid: false
    max-spaces-inside: 0
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation: disable
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
  key-duplicates: enable
  document-start: disable
  document-end: disable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 1
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
    level: warning
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy:
    allowed-values:
      - 'true'
      - 'false'
      - 'on'
    check-keys: false
ignore: |
  .git/
  .svn/
  .hg/
  _build/
  node_modules/
  venv/
  vendor/
  *.min.yaml
  charts/templates/
