const { FlatCompat } = require('@eslint/eslintrc'),
  eslint = require('@eslint/js'),
  globals = require('globals'),
  tseslint = require('typescript-eslint'),
  perfectionist = require('eslint-plugin-perfectionist'),
  json = require('@eslint/json'),
  markdown = require('@eslint/markdown'),
  css = require('@eslint/css'),
  prettierRecommended = require('eslint-plugin-prettier/recommended'),
  compat = new FlatCompat({ baseDirectory: __dirname });
module.exports = [
  {
    files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
    ...eslint.configs.recommended,
    languageOptions: { globals: globals.browser },
  },
  { files: ['**/*.js'], languageOptions: { sourceType: 'commonjs' } },
  { files: ['**/*.json'], plugins: { json }, language: 'json/json', ...json.configs.recommended },
  { files: ['**/*.jsonc'], plugins: { json }, language: 'json/jsonc', ...json.configs.recommended },
  { files: ['**/*.json5'], plugins: { json }, language: 'json/json5', ...json.configs.recommended },
  { files: ['**/*.md'], plugins: { markdown }, language: 'markdown/gfm', ...markdown.configs.recommended },
  { files: ['**/*.css'], plugins: { css }, language: 'css/css', ...css.configs.recommended },
  ...tseslint.config(
    eslint.configs.all,
    ...tseslint.configs.strictTypeChecked,
    ...tseslint.configs.stylisticTypeChecked,
    perfectionist.configs['recommended-natural'],
    {
      languageOptions: { parserOptions: { projectService: !0, tsconfigRootDir: __dirname } },
      rules: {
        '@typescript-eslint/array-type': ['error', { default: 'generic' }],
        '@typescript-eslint/consistent-return': 'off',
        '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
        '@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: !0 }],
        '@typescript-eslint/naming-convention': [
          'error',
          { format: ['camelCase'], selector: 'default' },
          { format: [], selector: 'property' },
          { format: ['PascalCase'], selector: 'typeLike' },
          { format: ['camelCase', 'PascalCase'], selector: 'import' },
          { format: ['camelCase', 'UPPER_CASE'], modifiers: ['const', 'global'], selector: 'variable' },
          { format: ['camelCase', 'PascalCase'], selector: 'variable', types: ['function'] },
          { filter: { match: !0, regex: '^_' }, format: [], selector: 'parameter' },
          { format: ['camelCase', 'PascalCase'], selector: 'function' },
        ],
        '@typescript-eslint/no-confusing-void-expression': ['error', { ignoreArrowShorthand: !0 }],
        '@typescript-eslint/no-magic-numbers': 'off',
        '@typescript-eslint/no-unsafe-type-assertion': 'off',
        '@typescript-eslint/no-unused-vars': [
          'error',
          { argsIgnorePattern: '^_', destructuredArrayIgnorePattern: '^_' },
        ],
        '@typescript-eslint/no-use-before-define': 'off',
        '@typescript-eslint/prefer-destructuring': 'off',
        '@typescript-eslint/strict-boolean-expressions': ['error', { allowNullableBoolean: !0 }],
        'capitalized-comments': 'off',
        'func-style': ['error', 'declaration', { allowArrowFunctions: !0 }],
        'id-length': ['error', { exceptions: ['x', 'y', 'z', 'w', 'i', 'j', 'k'] }],
        'max-lines-per-function': ['error', 150],
        'max-statements': ['error', 30],
        'no-console': 'error',
        'no-duplicate-imports': 'error',
        'no-inline-comments': 'off',
        'no-ternary': 'off',
        'no-undefined': 'off',
        'no-warning-comments': 'off',
        'one-var': 'off',
        'sort-imports': 'off',
        'sort-keys': 'off',
      },
    },
    { files: ['**/*.tsx'], rules: { 'max-lines': ['warn', 150] } },
    { files: ['**/*Datas.ts', '**/*.config.{js,ts}'], rules: { 'max-lines': 'off' } },
    { files: ['**/*.{test,spec}.{ts,tsx}'], rules: { '@typescript-eslint/no-magic-numbers': 'off' } }
  ),
  ...compat.config({ extends: ['next/core-web-vitals'], rules: { '@next/next/no-img-element': 'off' } }),
  prettierRecommended,
];
