complete -c fdf -s e -l extension -d 'filters based on extension, eg --extension .txt or -E txt' -r
complete -c fdf -s j -l threads -d 'Number of threads to use, defaults to available threads available on your computer' -r
complete -c fdf -s n -l max-results -d 'Retrieves the first eg 10 results, \'fdf  -n 10 \'.cache\' /' -r
complete -c fdf -s d -l depth -d 'Retrieves only traverse to x depth' -r
complete -c fdf -l generate -d 'Generate shell completions' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c fdf -l size -d 'Filter by file size (supports custom sizes with +/- prefixes)' -r -f -a "100\t'exactly 100 bytes'
1k\t'exactly 1 kilobyte (1000 bytes)'
1ki\t'exactly 1 kibibyte (1024 bytes)'
10mb\t'exactly 10 megabytes'
1gb\t'exactly 1 gigabyte'
+1m\t'larger than 1MB'
+10mb\t'larger than 10MB'
+1gib\t'larger than 1GiB'
-500k\t'smaller than 500KB'
-10mb\t'smaller than 10MB'
-1gib\t'smaller than 1GiB'"
complete -c fdf -s t -l type -d 'Filter by file type' -r -f -a "d\t'Directory'
u\t'Unknown type'
l\t'Symbolic link'
f\t'Regular file'
p\t'Pipe/FIFO'
c\t'Character device'
b\t'Block device'
s\t'Socket'
e\t'Empty file'
x\t'Executable file'"
complete -c fdf -s H -l hidden -d 'Shows hidden files eg .gitignore or .bashrc, defaults to off'
complete -c fdf -s S -l sort -d 'Sort the entries alphabetically (this has quite the performance cost)'
complete -c fdf -s s -l case-sensitive -d 'Enable case-sensitive matching, defaults to false'
complete -c fdf -s a -l absolute-path -d 'Starts with the directory entered being resolved to full'
complete -c fdf -s I -l include-dirs -d 'Include directories, defaults to off'
complete -c fdf -s L -l follow -d 'Include symlinks in traversal,defaults to false'
complete -c fdf -l nocolour -d 'Disable colouring output when sending to terminal'
complete -c fdf -s g -l glob -d 'Use a glob pattern,defaults to off'
complete -c fdf -s p -l full-path -d 'Use a full path for regex matching, default to false'
complete -c fdf -s F -l fixed-strings -d 'Use a fixed string not a regex, defaults to false'
complete -c fdf -l show-errors -d 'Show errors when traversing'
complete -c fdf -l same-file-system -d 'Only traverse the same filesystem as the starting directory'
complete -c fdf -s h -l help -d 'Print help (see more with \'--help\')'
complete -c fdf -s V -l version -d 'Print version'
