video_presets:
  fast:
    codec: Vp9
    crf: 25
    bitrate: null
    audio_codec: Opus
    audio_bitrate: 128k
    preset: fast
    two_pass: false
    extra_args: []
  slow:
    codec: Av1
    crf: 20
    bitrate: null
    audio_codec: Opus
    audio_bitrate: 128k
    preset: slow
    two_pass: true
    extra_args: []
  medium:
    codec: H265
    crf: 23
    bitrate: null
    audio_codec: Opus
    audio_bitrate: 128k
    preset: medium
    two_pass: false
    extra_args: []
  ultrafast:
    codec: H265
    crf: 28
    bitrate: null
    audio_codec: Opus
    audio_bitrate: 128k
    preset: ultrafast
    two_pass: false
    extra_args: []
  veryslow:
    codec: Av1
    crf: 18
    bitrate: null
    audio_codec: Opus
    audio_bitrate: 96k
    preset: veryslow
    two_pass: true
    extra_args: [--fps 60]
image_presets:
  lossless:
    quality: 99
    optimize: true
    progressive: false
    lossless: true
  web:
    quality: 85
    optimize: true
    progressive: true
    lossless: false
  high:
    quality: 90
    optimize: true
    progressive: false
    lossless: false
default_settings:
  output_dir: null
  overwrite: false
  parallel_jobs: 16
  preserve_metadata: true
  backup_originals: false
