video_presets:
  slow:
    codec: H264
    crf: 20
    bitrate: null
    audio_codec: opus
    audio_bitrate: 192k
    preset: slow
    two_pass: true
    extra_args: []
  veryslow:
    codec: H265
    crf: 18
    bitrate: null
    audio_codec: opus
    audio_bitrate: 256k
    preset: veryslow
    two_pass: true
    extra_args: []
  medium:
    codec: H264
    crf: 23
    bitrate: null
    audio_codec: opus
    audio_bitrate: 128k
    preset: medium
    two_pass: false
    extra_args: []
  fast:
    codec: H264
    crf: 25
    bitrate: null
    audio_codec: opus
    audio_bitrate: 128k
    preset: fast
    two_pass: false
    extra_args: []
  ultrafast:
    codec: H264
    crf: 28
    bitrate: null
    audio_codec: opus
    audio_bitrate: 128k
    preset: ultrafast
    two_pass: false
    extra_args: []
  optimal:
    codec: av1
    audio_codec: opus
    audio_bitrate: 128k
    preset: slow
    resolution: 1920x1080
    two_pass: true
    bitrate: null
    crf: 28
    extra_args: []
image_presets:
  lossless:
    quality: 100
    optimize: true
    progressive: true
    lossless: true
  web:
    quality: 85
    optimize: true
    progressive: true
    lossless: false
  high:
    quality: 95
    optimize: true
    progressive: false
    lossless: false
default_settings:
  output_dir: null
  overwrite: false
  parallel_jobs: 16
  preserve_metadata: true
  backup_originals: false
