# Specifies the network interface to use for the LocalIP readout
interface = "enp4s0"
# Lengthen uptime output
long_uptime = false
# Lengthen shell output
long_shell = false
# Lengthen kernel output
long_kernel = false
# Shorten gpu output
shorter_gpu = true
# Shorten cpu output
shorter_cpu = true
# Toggle between displaying the current shell or your user's default one.
current_shell = true
# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true
memory_percentage = true
disk_space_percentage = true

# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
#   - GPU
# Example:
show = [
  "Kernel",
  "Distribution",
  "DesktopEnvironment",
  "Shell",
  "Terminal",
  "Processor",
  "ProcessorLoad",
  "GPU",
  "Memory",
  "DiskSpace",
  "LocalIP",
]
