compile-bytecode = true
link-mode = "hardlink"
prerelease = "if-necessary-or-explicit"
preview = true
python-preference = "system"
resolution = "highest"
upgrade = true
fork-strategy = "fewest"
add-bounds = "lower"
allow-insecure-host = ["localhost:8080"]
concurrent-downloads = 25
native-tls = true
extra-build-variables = { PYTHON = { PYTHONOPTIMIZE = "2", PYTHON_JIT = "1", PYTORCH_ENABLE_MPS_FALLBACK = "1", PYTHON_DISABLE_REMOTE_DEBUG = "1", PYTHONIOENCODING = "UTF-8" } }

[pip]
compile-bytecode = true
fork-strategy = "fewest"
link-mode = "hardlink"
prerelease = "if-necessary-or-explicit"
resolution = "highest"
strict = true
system = true
torch-backend = "cu126"
upgrade = true
verify-hashes = false
index-strategy = "unsafe-best-match"
allow-empty-requirements = true
all-extras = false
annotation-style = "line"
no-annotate = true
no-header = true
break-system-packages = false
