# .github/workflows/automerge-dependabot.yml
name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened]
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr review --approve ${{ github.event.pull_request.html_url }}
          gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
