# https://github.com/marketplace/actions/image-optimizer-action
name: Optimize Images
on:
  workflow_dispatch:
  #schedule: [{cron: "0 0 * * 0"}]
  pull_request:
    paths:
      - '**/*.{svg,png,jpg,jpeg,gif,webp,avif}'
  push:
    paths:
      - '**/*.{svg,png,jpg,jpeg,gif,webp,avif}'  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: stellasoftio/image-optimizer-action
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      # Compress images
      - name: Compress Images
        id: compress-images
        uses: stellasoftio/image-optimizer-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          export-webp: true
          export-avif: true
          compress-png: true
          compress-svg: true
          compress-jpg: true
          compress-webp: true
          compress-avif: true
          replace-original-after-export-webp: true

      # Create pull request if any images were compressed
      - name: Create New Pull Request If Needed
        if: steps.compress-images.outputs.markdown_report != ''
        #if: steps.compress-images.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.compress-images.outputs.markdown_report }}
